
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "35043:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "35025:1025"
      - "35026:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> sensiolabs/gotenberg-bundle ###
  gotenberg:
    ports:
      - "35030:3000"
###< sensiolabs/gotenberg-bundle ###
