<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260428083639 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE notes_id_seq CASCADE');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('DROP TABLE notes');
        $this->addSql('ALTER TABLE client ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE client ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_client_user RENAME TO IDX_C7440455A76ED395');
        $this->addSql('ALTER TABLE invoice ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE invoice ALTER status DROP DEFAULT');
        $this->addSql('ALTER INDEX uniq_invoice_number RENAME TO UNIQ_9065174496901F54');
        $this->addSql('ALTER INDEX idx_invoice_client RENAME TO IDX_9065174419EB6921');
        $this->addSql('ALTER INDEX idx_invoice_user RENAME TO IDX_90651744A76ED395');
        $this->addSql('ALTER TABLE invoice_line ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice_line ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE invoice_line ALTER unit DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice_line ALTER position DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_invoice_line_invoice RENAME TO IDX_D3D1D6932989F1FD');
        $this->addSql('ALTER INDEX idx_invoice_line_product RENAME TO IDX_D3D1D6934584665A');
        $this->addSql('ALTER TABLE product ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE product ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE product ALTER unit DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_product_user RENAME TO IDX_D34A04ADA76ED395');
        $this->addSql('ALTER TABLE users DROP cgv');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE notes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE notes (id INT DEFAULT nextval(\'notes_id_seq\'::regclass) NOT NULL, user_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE client ALTER id SET DEFAULT nextval(\'client_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE client ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_c7440455a76ed395 RENAME TO idx_client_user');
        $this->addSql('ALTER TABLE invoice ALTER id SET DEFAULT nextval(\'invoice_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE invoice ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE invoice ALTER status SET DEFAULT \'draft\'');
        $this->addSql('ALTER INDEX uniq_9065174496901f54 RENAME TO uniq_invoice_number');
        $this->addSql('ALTER INDEX idx_90651744a76ed395 RENAME TO idx_invoice_user');
        $this->addSql('ALTER INDEX idx_9065174419eb6921 RENAME TO idx_invoice_client');
        $this->addSql('ALTER TABLE invoice_line ALTER id SET DEFAULT nextval(\'invoice_line_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE invoice_line ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE invoice_line ALTER unit SET DEFAULT \'piece\'');
        $this->addSql('ALTER TABLE invoice_line ALTER "position" SET DEFAULT 0');
        $this->addSql('ALTER INDEX idx_d3d1d6932989f1fd RENAME TO idx_invoice_line_invoice');
        $this->addSql('ALTER INDEX idx_d3d1d6934584665a RENAME TO idx_invoice_line_product');
        $this->addSql('ALTER TABLE product ALTER id SET DEFAULT nextval(\'product_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE product ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE product ALTER unit SET DEFAULT \'piece\'');
        $this->addSql('ALTER INDEX idx_d34a04ada76ed395 RENAME TO idx_product_user');
        $this->addSql('ALTER TABLE users ADD cgv TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
    }
}
